name: oauth2-proxy
version: 3.2.6
apiVersion: v1
appVersion: 5.1.0
home: https://oauth2-proxy.github.io/oauth2-proxy/
description: A reverse proxy that provides authentication with Google, Github or other providers
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
sources:
- https://github.com/oauth2-proxy/oauth2-proxy
- https://github.com/oauth2-proxy/manifests
maintainers:
- email: cedric@desaintmartin.fr
  name: desaintmartin
- name: tlawrie
engine: gotpl
kubeVersion: ">=1.9.0-0"
